### ISSUE TITLE
installing compat-5.3.h by luarocks

### ISSUE THREAD

**Issue by fperrad** [lunarmodules/lua-compat-5.3#62]
The Debian/Ubuntu package `lua-compat53-dev` installs the files `compat-5.3.h` and `compat-5.3.c` into the proper location, see <https://packages.debian.org/sid/amd64/lua-compat53-dev/filelist>.
So, these files can be included when building native modules.

Is it possible to do the same with `luarocks` and a rockspec ?

**Comment by hishamhm** [comment]
> Is it possible to do the same with luarocks and a rockspec ?

No, LuaRocks does not install general C libraries, only Lua modules. I've always avoided functioning as general-purpose package manager for arbitrary libraries, especially to avoid clashing with distro packages.
