### ISSUE TITLE
Unable to install from luarocks on Windows: C4047 issue on liolib.c

### ISSUE THREAD

**Issue by manoaratefy** [lunarmodules/lua-compat-5.3#65]
Hello,

I'm not very good at LUA or C compilation. I tried to install this library from luarocks, with both Visual C++ Build Tools 2017 and 2022. Same triggered the same error:

```
C:\myluaproject\luarocks>luarocks install compat53
Installing https://luarocks.org/compat53-0.13-1.src.rock

cl /nologo /MD /O2 -c -Folstrlib.obj -IC:\myluaproject\luajit\inc lstrlib.c
lstrlib.c
link -dll -subsystem:windows,5.01 -def:string.def -out:compat53/string.dll C:\myluaproject\luajit\lib/lua51.lib lstrlib.obj
Microsoft (R) Incremental Linker Version 14.16.27051.0
Copyright (C) Microsoft Corporation.  All rights reserved.

   Création de la bibliothèque compat53/string.lib et de l'objet compat53/string.exp
cl /nologo /MD /O2 -c -Foliolib.obj -IC:\myluaproject\luajit\inc liolib.c
liolib.c
liolib.c(280): warning C4047: '=' : les niveaux d'indirection de 'FILE *' et de 'int' sont différents
link -dll -subsystem:windows,5.01 -def:io.def -out:compat53/io.dll C:\myluaproject\luajit\lib/lua51.lib liolib.obj
Microsoft (R) Incremental Linker Version 14.16.27051.0
Copyright (C) Microsoft Corporation.  All rights reserved.

io.def : error LNK2001: symbole externe non résolu luaopen_compat53_io
compat53/io.lib : fatal error LNK1120: 1 externes non résolus

Error: Build error: Failed compiling module compat53/io.dll
```
Is this a Visual C++ version mismatch or a bug?

Thanks in advance.

**Comment by hishamhm** [comment]
Thank you for the report! This looks like a rockspec build issue specific to LuaJIT on Windows: 

For LuaJIT, we do not want to have the compat io library, so we disable the entrypoint function `luaopen_compat53_io`  with an #ifdef in the C code.

However, LuaRocks automatically generates the Windows `.def` files for compilation, so it produces an `io.def` file expecting the `luaopen_compat53_io` function, which is then not found and causes `link` to fail.

As a temporary workaround, you can:

(1) download the rockspec file: https://raw.githubusercontent.com/lunarmodules/lua-compat-5.3/master/rockspecs/compat53-0.13-1.rockspec
(2) remove the line `["compat53.io"] = "liolib.c",`
(3) build it directly with `luarocks build compat53-0.13-1.rockspec`

Please let us know if that works! Thanks!

**Comment by manoaratefy** [comment]
Compilation is successful. I guess io related functions will be unavailable, right?
